### ISSUE TITLE
Export algorithms to other apps

### ISSUE THREAD

**Issue by anthonygtellez** [splunk/splunk-3D-graph-network-topology-viz#10]
update default.meta to export algorithms for use in other apps.

Currently using the algorithms: GraphLabelPropagation & GraphConnectedComponents cause errors when they are run outside the app. 

I suggest the following fix to `default.meta`:

```
[algos]
access = read : [ * ], write : [ admin ]
export = system
```

**Comment by pdrieger** [comment]
done for 1.2 release
