### ISSUE TITLE
Labels & token passthrough for nodes

### ISSUE THREAD

**Issue by omaliphant** [splunk/splunk-3D-graph-network-topology-viz#39]
when visualizing data it would be super helpful to have a toggle labels option for the nodes.

when exploring data through graphs/visualization to be able to quickly see a nodes name/value and then click on it to expand it in a new view with a token pass through would make this extremely powerful.

is that possible? It could almost be like some sort of minority report style interface for data set review which would be awesome!
thanks!

**Comment by pdrieger** [comment]
Hi @omaliphant you can use drilldown and a token from the viz by enabling it in your dashboard panel like adding these options:
        <option name="drilldown">all</option>
        <drilldown>
          <set token="tok">$row.src$</set>
        </drilldown>
Then if you click on a node in your graph it should populate a token with the value from a field named src. Then you can use this token on your dashboard to be used in another panel or visualisation.

For your first question: would you like to toggle the label and then see them all showing up? If yes, then for larger graphs you will likely have a very cluttered or crowded screen full of overlapping text that is very hard to read. Would you still find this useful?

**Comment by omaliphant** [comment]
Thank you!And for Q1: Yes we would love to have a toggle option for enabling labels for all nodes.Would be super useful.Thanks again!Sent from my iPhoneOn 6 Sep 2023, at 09:47, pdrieger ***@***.***> wrote:﻿
Hi @omaliphant you can use drilldown and a token from the viz by enabling it in your dashboard panel like adding these options:
all

$row.src$

Then if you click on a node in your graph it should populate a token with the value from a field named src. Then you can use this token on your dashboard to be used in another panel or visualisation.
For your first question: would you like to toggle the label and then see them all showing up? If yes, then for larger graphs you will likely have a very cluttered or crowded screen full of overlapping text that is very hard to read. Would you still find this useful?
