### ISSUE TITLE
Performance improvement 1: canvas switch from 2D to 3D

### ISSUE THREAD

**Issue by pdrieger** [splunk/splunk-3D-graph-network-topology-viz#4]
Research about improving the stability and performance of the app to check if the initialisation of the 2 available renderers (2D and 3D) can be modified to have not both of them initialised to be switched, but to better initialise on demand when the switch happens and preventing of running a non-visible but resource consuming panel.

**Comment by edro15** [comment]
Performance improvement has been already provided by commit 8e6be7df1e7474bb30ee2668747fcd85d36cfaaf after some testing and troubleshooting. At this stage, context switching does not have a relevant impact on consuming resources.
