### ISSUE TITLE
Drill down onNodeClick

### ISSUE THREAD

**Issue by pdrieger** [splunk/splunk-3D-graph-network-topology-viz#6]
In order to drill down from the visulization to interact in a dashboard an added drill down behaviour would be great to set a dashboard token with the primary node information (typically the node id that was taken from the search results). Click on a node maintains the default viz behaviour but adds also the setting of a dashboard token.

**Comment by edro15** [comment]
Already provided by the visualization. It only requires opportune drilldown configuration in your dashboard.

**Example**
Considering as viz search `<search> | stats count by src dest`, you can configure a token named "nodeid" as shown below.
<img width="557" alt="Screenshot 2020-05-06 at 12 30 22" src="https://user-images.githubusercontent.com/25966020/81167360-5fe58d80-8f95-11ea-86a1-10472fcc8b69.png">

In this way, when clicking on a node, your token "nodeid" will have that node id as value.
<img width="1373" alt="Screenshot 2020-05-06 at 12 41 45" src="https://user-images.githubusercontent.com/25966020/81168264-f8304200-8f96-11ea-9687-555607a0fb63.png">
